patgod85_team_team_api:
    resource: "@Patgod85TeamBundle/Controller/TeamRESTController.php"
    type:   rest
    prefix:   /api

patgod85_team:
    resource: "@Patgod85TeamBundle/Resources/config/routing.yml"
    prefix:   /

patgod85_user_user_api:
    resource: "@Patgod85UserBundle/Controller/UserRESTController.php"
    type:   rest
    prefix:   /api

patgod85_user:
    resource: "@Patgod85UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

